use crate::intelligence::graph::KnowledgeGraph;
use crate::intelligence::librarian::{Librarian, OrbEntry};
use crate::intelligence::scribe::{GatekeeperResult, Scribe};
use crate::pipeline::tunnel::WormholeTunnel;
use crate::storage::journal::Journal;
use crate::storage::journal::PendingCatalogEntry;
use crate::storage::keystore::Keystore;
use crate::storage::shelf::OrbShelf;
use crate::types::error::TunnelError;
use crate::types::fact::{AnswerFact, Foresight};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Clone, Debug, Default, Deserialize, PartialEq, Eq, Serialize)]
pub enum ContentType {
    #[default]
    Text,
    Table,
    TimeSeries,
    Code,
}

impl ContentType {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Text => "text",
            Self::Table => "table",
            Self::TimeSeries => "time_series",
            Self::Code => "code",
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        match value {
            "text" => Some(Self::Text),
            "table" => Some(Self::Table),
            "time_series" | "timeseries" => Some(Self::TimeSeries),
            "code" => Some(Self::Code),
            _ => None,
        }
    }
}

/// Ingestion request — everything the Gatekeeper needs to commit content.
///
/// Caller is responsible for chunking large documents before calling ingest().
/// One chunk → one orb. Chunk size is caller-defined (typical: 4 KB of text).
/// Single-document ingestion passes chunks with one element.
///
/// Serializable minus `chunks` — the journal keeps this (without the raw
/// content) so reconcile_catalog() can replay a failed catalog registration
/// without needing the original caller to still be around.
#[derive(Deserialize, Serialize)]
pub struct IngestionRequest {
    /// Who is ingesting — agent identifier or user handle.
    pub agent_id: String,
    /// Subject / topic tag. e.g. "patient_record", "threat_intel", "contract".
    pub topic: String,
    /// Domain. e.g. "medical", "legal", "security", "finance".
    pub domain: String,
    /// ISO date string representing when this content originates. e.g. "2026-05-29".
    pub date: String,
    /// Content format: "text", "markdown", "json", "pdf".
    pub format: String,
    /// Data classification: public, internal, sensitive, regulated, or secret.
    pub classification: String,
    /// 100-word summary. Used as embedding anchor and graph entity source.
    /// NOT stored as content. Purely for finding this chain at retrieval time.
    pub summary: String,
    /// Optional atomic verifiable facts derived from the content.
    /// Each string is one independently-verifiable statement.
    /// Example: ["patient was admitted", "admission date: 2026-05-01", "symptom: chest pain"]
    /// If empty, only the summary is embedded (existing behavior).
    pub answer_facts: Vec<String>,
    /// Structured fact atoms with verification metadata. Legacy answer_facts are
    /// converted to unverified atoms before catalog storage.
    pub answer_fact_atoms: Vec<AnswerFact>,
    /// Time-bounded predictive facts retrieved by relevance date.
    pub foresights: Vec<Foresight>,
    /// Who authored or generated the summary. Defaults should be the ingesting
    /// agent_id when callers do not have a separate author.
    pub summary_author: String,
    /// Model identifier when the summary was generated by a model.
    pub summary_model: Option<String>,
    /// Whether a human/operator has verified the summary.
    pub summary_verified: bool,
    /// Timestamp for summary verification, if known.
    pub summary_verified_at: Option<String>,
    /// Pinned memories never demote to warm/cold lifecycle tiers.
    pub pinned: Option<bool>,
    /// Semantic content type. Defaults to Text when omitted by adapters.
    pub content_type: Option<ContentType>,
    /// Natural-language interpretation used for indexing table content.
    pub table_summary: Option<String>,
    /// Raw content chunks. One chunk per orb.
    /// Caller splits large documents; Gatekeeper seals each chunk as one orb.
    #[serde(skip_serializing, default)]
    pub chunks: Vec<Vec<u8>>,
}

/// Returned on successful ingestion.
pub struct IngestionResult {
    /// The chain identifier. All orbs in this ingestion share this parent_id.
    pub parent_id: String,
    /// Sealed orb IDs in sequence order.
    pub orb_ids: Vec<String>,
}

/// Gatekeeper — the only entry point for writing content into Venturi.
///
/// Orchestrates the full atomic commit sequence:
///
///   1. Journal.open_ingestion — write-ahead log entry opened (IN_PROGRESS)
///   2. For each chunk:
///      a. WormholeTunnel.seal_chunk — Gate2(compress) + Gate3(encrypt)
///      b. OrbShelf.store           — sealed orb written to disk
///      c. Keystore.deposit         — chain key deposited (exit gate only)
///      d. Journal.record_orb       — orb recorded in WAL
///   3. Journal.commit_ingestion    — WAL status → COMPLETE (atomic)
///   4. Librarian.register_orb×N   — catalog entries with embeddings
///   5. KnowledgeGraph.ingest_summary — entity/relationship extraction
///   6. Scribe.record_ingestion    — audit event logged
///
/// On failure in steps 1–3: journal is rolled back, orphaned orbs and keys
/// are cleaned from disk and keystore. Steps 4–6 failures are soft — data
/// is already durable on disk; catalog can be rebuilt.
///
/// Startup recovery: call recover_incomplete() before first ingest() to clean
/// up any IN_PROGRESS entries left by a prior crash.
pub struct Gatekeeper {
    journal: Journal,
    keystore: Keystore,
    scribe: Scribe,
    shelf: OrbShelf,
    tunnel: WormholeTunnel,
    librarian: Librarian,
    graph: KnowledgeGraph,
}

pub struct GatekeeperOpenConfig<'a> {
    pub shelf_root: &'a str,
    pub journal_db: &'a str,
    pub keystore_db: &'a str,
    pub librarian_db: &'a str,
    pub scribe_db: &'a str,
    pub graph_db: &'a str,
    pub ollama_url: &'a str,
    pub embedding_model: Option<&'a str>,
    pub embedding_dim: Option<usize>,
}

impl Gatekeeper {
    /// Open all subsystems. Each component gets its own isolated database path.
    ///
    /// Recommended layout:
    ///   shelf_root   → /var/venturi/shelf/
    ///   journal_db   → /var/venturi/journal.db
    ///   keystore_db  → /var/venturi/keys/keystore.db   (chmod 600, separate dir)
    ///   librarian_db → /var/venturi/librarian.db
    ///   scribe_db    → /var/venturi/scribe.db
    ///   graph_db     → /var/venturi/graph.db
    pub fn open(cfg: GatekeeperOpenConfig<'_>) -> Result<Self, TunnelError> {
        Ok(Self {
            journal: Journal::open(cfg.journal_db)?,
            keystore: Keystore::open(cfg.keystore_db)?,
            scribe: Scribe::open(cfg.scribe_db)?,
            shelf: OrbShelf::new(cfg.shelf_root),
            tunnel: WormholeTunnel::new(),
            librarian: Librarian::open(
                cfg.librarian_db,
                cfg.ollama_url,
                cfg.embedding_model,
                cfg.embedding_dim,
            )?,
            graph: KnowledgeGraph::open(cfg.graph_db, cfg.ollama_url)?,
        })
    }

    /// Ingest content into Venturi.
    ///
    /// Thread-safety: Gatekeeper takes &mut self. Use one Gatekeeper per thread
    /// or wrap in a Mutex for concurrent ingestion.
    pub fn ingest(&mut self, req: IngestionRequest) -> Result<IngestionResult, TunnelError> {
        Self::validate_request(&req)?;

        let parent_id = Uuid::new_v4().to_string();
        let chain_length = req.chunks.len() as u32;
        let request_json = serde_json::to_string(&req).unwrap_or_default();

        // Step 1: Open WAL entry
        self.journal
            .open_ingestion(&parent_id, chain_length, &req.agent_id, &request_json)?;

        // Steps 2a–2d: Seal all chunks atomically
        let seal_result = self.seal_chain(&parent_id, chain_length, &req);

        match seal_result {
            Ok(sealed) => self.complete_ingestion(parent_id, chain_length, &req, sealed),
            Err(e) => self.fail_ingestion(&parent_id, chain_length, &req, e),
        }
    }

    // ── Read-path accessors (used by api.rs for retrieval) ────────────────────
    // These share the same DB connections opened at Gatekeeper::open().
    // api.rs uses these rather than opening independent connections.

    pub fn librarian(&self) -> &Librarian {
        &self.librarian
    }
    pub fn librarian_mut(&mut self) -> &mut Librarian {
        &mut self.librarian
    }
    pub fn keystore(&self) -> &Keystore {
        &self.keystore
    }
    pub fn shelf(&self) -> &OrbShelf {
        &self.shelf
    }
    pub fn graph(&self) -> &KnowledgeGraph {
        &self.graph
    }
    pub fn scribe(&self) -> &Scribe {
        &self.scribe
    }

    /// Recover any IN_PROGRESS ingestions left by a prior crash.
    /// Call once on startup before accepting new ingestion requests.
    pub fn recover_incomplete(&self) -> Result<u32, TunnelError> {
        let incomplete = self.journal.in_progress()?;
        let count = incomplete.len() as u32;

        for entry in incomplete {
            // Remove any orbs that made it to disk
            for orb_id in &entry.orb_ids {
                let _ = self.shelf.remove(orb_id);
            }
            // Remove any keys deposited for this chain
            let _ = self.keystore.remove_by_parent(&entry.parent_id);
            // Mark journal entry as failed
            let _ = self.journal.rollback_ingestion(
                &entry.parent_id,
                "recovered from crash: IN_PROGRESS on startup",
            );
        }

        Ok(count)
    }

    /// Replay catalog registration for any committed ingestion whose Librarian
    /// entry, graph index, or audit record never landed (steps 4–6 of ingest()
    /// are best-effort by design; this is what actually makes them recoverable
    /// instead of "durable on disk but unfindable" forever). Call once on
    /// startup, alongside recover_incomplete().
    pub fn reconcile_catalog(&mut self) -> Result<u32, TunnelError> {
        let pending = self.journal.pending_catalog_registration()?;
        let mut reconciled = 0u32;

        for entry in pending {
            if self.reconcile_one(&entry) {
                reconciled += 1;
            }
        }
        Ok(reconciled)
    }

    fn reconcile_one(&mut self, entry: &PendingCatalogEntry) -> bool {
        let Some(request_json) = entry.request_json.as_deref() else {
            return false; // journaled before this column existed — nothing to replay
        };
        let Ok(mut req) = serde_json::from_str::<IngestionRequest>(request_json) else {
            return false; // corrupt metadata — leave for manual inspection
        };
        req.chunks = Vec::new();

        let key_id = match self.keystore.retrieve_by_parent(&entry.parent_id) {
            Ok(Some(key_id)) => key_id,
            _ => return false, // key already purged (expired/rolled back) — nothing to reconcile
        };

        if self
            .register_catalog(
                &entry.orb_ids,
                &key_id,
                &entry.parent_id,
                entry.expected_n,
                &req,
            )
            .is_err()
        {
            return false; // still failing — retried again on next startup
        }
        let _ = self.journal.mark_catalog_registered(&entry.parent_id);
        if req.classification != "secret" {
            let _ = self
                .graph
                .ingest_summary(&entry.parent_id, Self::indexing_summary(&req));
        }
        let _ = self.scribe.record_ingestion(
            &req.agent_id,
            &entry.parent_id,
            entry.expected_n,
            &req.summary,
            GatekeeperResult::Pass,
        );
        true
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    fn complete_ingestion(
        &mut self,
        parent_id: String,
        chain_length: u32,
        req: &IngestionRequest,
        sealed: SealedChain,
    ) -> Result<IngestionResult, TunnelError> {
        if let Err(e) = self.journal.commit_ingestion(&parent_id) {
            let _ = self.rollback(&parent_id, &sealed.orb_ids, &e.to_string());
            self.audit_ingestion_failure(req, &parent_id, chain_length, &e);
            return Err(e);
        }

        if self
            .register_catalog(
                &sealed.orb_ids,
                &sealed.key_id,
                &parent_id,
                chain_length,
                req,
            )
            .is_ok()
        {
            // Only mark the catalog as registered on success — leaving it
            // unmarked on failure is what lets reconcile_catalog() find and
            // replay it later instead of the orb becoming permanently
            // durable-but-unfindable.
            let _ = self.journal.mark_catalog_registered(&parent_id);
        }
        if req.classification != "secret" {
            let _ = self
                .graph
                .ingest_summary(&parent_id, Self::indexing_summary(req));
        }
        let _ = self.scribe.record_ingestion(
            &req.agent_id,
            &parent_id,
            chain_length,
            &req.summary,
            GatekeeperResult::Pass,
        );

        Ok(IngestionResult {
            parent_id,
            orb_ids: sealed.orb_ids,
        })
    }

    fn fail_ingestion(
        &self,
        parent_id: &str,
        chain_length: u32,
        req: &IngestionRequest,
        error: TunnelError,
    ) -> Result<IngestionResult, TunnelError> {
        let _ = self.rollback(parent_id, &[], &error.to_string());
        self.audit_ingestion_failure(req, parent_id, chain_length, &error);
        Err(error)
    }

    fn audit_ingestion_failure(
        &self,
        req: &IngestionRequest,
        parent_id: &str,
        chain_length: u32,
        error: &TunnelError,
    ) {
        let _ = self.scribe.record_ingestion(
            &req.agent_id,
            parent_id,
            chain_length,
            &req.summary,
            GatekeeperResult::Fail(error.to_string()),
        );
    }

    fn validate_request(req: &IngestionRequest) -> Result<(), TunnelError> {
        if req.chunks.is_empty() {
            return Self::reject("ingestion request contains no chunks");
        }

        for (field, value) in [
            ("agent_id", &req.agent_id),
            ("topic", &req.topic),
            ("domain", &req.domain),
            ("date", &req.date),
            ("format", &req.format),
            ("classification", &req.classification),
            ("summary", &req.summary),
            ("summary_author", &req.summary_author),
        ] {
            if value.trim().is_empty() {
                return Self::reject(&format!("{} is required", field));
            }
        }

        if req.summary_verified_at.is_some() && !req.summary_verified {
            return Self::reject("summary_verified_at requires summary_verified");
        }
        if !is_iso_date(&req.date) {
            return Self::reject("date must be a valid ISO date (YYYY-MM-DD)");
        }
        Self::validate_foresights(&req.foresights)?;
        Self::validate_content_type(req)?;

        let summary_words = req.summary.split_whitespace().count();
        if summary_words > 100 {
            return Self::reject("summary exceeds 100 words");
        }

        match req.format.as_str() {
            "text" | "md" | "markdown" | "json" | "pdf" | "csv" | "html" => {}
            _ => {
                return Self::reject(
                    "format must be one of text, md, markdown, json, pdf, csv, html",
                )
            }
        }

        match req.classification.as_str() {
            "public" | "internal" | "sensitive" | "regulated" | "secret" => Ok(()),
            _ => Self::reject(
                "classification must be one of public, internal, sensitive, regulated, secret",
            ),
        }
    }

    fn reject<T>(reason: &str) -> Result<T, TunnelError> {
        Err(TunnelError::GatekeeperRejected {
            reason: reason.to_string(),
        })
    }

    fn seal_chain(
        &mut self,
        parent_id: &str,
        chain_length: u32,
        req: &IngestionRequest,
    ) -> Result<SealedChain, TunnelError> {
        let mut orb_ids = Vec::with_capacity(req.chunks.len());
        let chain_key = self.tunnel.generate_chain_key();
        let key_id = Uuid::new_v4().to_string();

        self.keystore.deposit(&key_id, parent_id, &chain_key)?;

        for (i, chunk) in req.chunks.iter().enumerate() {
            let sequence = (i + 1) as u32;

            let orb = self.tunnel.seal_chunk_with_key(
                chunk.to_vec(),
                parent_id.to_string(),
                sequence,
                chain_length,
                &chain_key,
            )?;

            let orb_id = orb.id.as_hex();

            // Write sealed orb blob to disk
            self.shelf.store(&orb)?;

            // Record this orb in the WAL
            self.journal.record_orb(parent_id, &orb_id, sequence)?;

            orb_ids.push(orb_id);
        }

        Ok(SealedChain { key_id, orb_ids })
    }

    fn register_catalog(
        &mut self,
        orb_ids: &[String],
        key_id: &str,
        parent_id: &str,
        chain_length: u32,
        req: &IngestionRequest,
    ) -> Result<(), TunnelError> {
        for (i, orb_id) in orb_ids.iter().enumerate() {
            self.librarian.register_orb(OrbEntry {
                orb_id: orb_id.clone(),
                key_id: key_id.to_string(),
                topic: req.topic.clone(),
                domain: req.domain.clone(),
                date: req.date.clone(),
                parent_id: parent_id.to_string(),
                sequence: (i + 1) as u32,
                chain_length,
                format: req.format.clone(),
                classification: req.classification.clone(),
                content_type: Self::content_type(req).as_str().to_string(),
                pinned: req.pinned.unwrap_or(false),
                owner_agent_id: req.agent_id.clone(),
                summary: Self::indexing_summary(req).to_string(),
                answer_facts: Self::fact_atoms(req),
                summary_author: req.summary_author.clone(),
                summary_model: req.summary_model.clone(),
                summary_verified: req.summary_verified,
                summary_verified_at: req.summary_verified_at.clone(),
                foresights: req.foresights.clone(),
            })?;
        }
        Ok(())
    }

    fn validate_foresights(foresights: &[Foresight]) -> Result<(), TunnelError> {
        for foresight in foresights {
            if foresight.foresight_text.trim().is_empty() {
                return Self::reject("foresight_text is required");
            }
            if foresight.relevant_from.trim().is_empty() {
                return Self::reject("foresight relevant_from is required");
            }
            if foresight.relevant_until.trim().is_empty() {
                return Self::reject("foresight relevant_until is required");
            }
            if !is_iso_date(&foresight.relevant_from) || !is_iso_date(&foresight.relevant_until) {
                return Self::reject("foresight dates must be valid ISO dates (YYYY-MM-DD)");
            }
            if foresight.relevant_from > foresight.relevant_until {
                return Self::reject("foresight relevant_from must be <= relevant_until");
            }
        }
        Ok(())
    }

    fn validate_content_type(req: &IngestionRequest) -> Result<(), TunnelError> {
        match Self::content_type(req) {
            ContentType::Table => {
                let Some(summary) = req.table_summary.as_deref() else {
                    return Self::reject("table_summary is required when content_type is table");
                };
                if summary.trim().is_empty() {
                    return Self::reject("table_summary is required when content_type is table");
                }
                if summary.split_whitespace().count() > 100 {
                    return Self::reject("table_summary exceeds 100 words");
                }
                Ok(())
            }
            _ => Ok(()),
        }
    }

    fn content_type(req: &IngestionRequest) -> ContentType {
        req.content_type.clone().unwrap_or_default()
    }

    fn indexing_summary(req: &IngestionRequest) -> &str {
        if Self::content_type(req) == ContentType::Table {
            req.table_summary.as_deref().unwrap_or(&req.summary)
        } else {
            &req.summary
        }
    }

    fn fact_atoms(req: &IngestionRequest) -> Vec<AnswerFact> {
        let mut facts: Vec<AnswerFact> = req
            .answer_facts
            .iter()
            .map(|fact| AnswerFact {
                fact: fact.clone(),
                verified: false,
                verified_by: None,
            })
            .collect();
        facts.extend(req.answer_fact_atoms.clone());
        facts
    }

    /// Best-effort rollback: remove shelf orbs and keystore keys for this chain.
    fn rollback(
        &self,
        parent_id: &str,
        orb_ids: &[String],
        reason: &str,
    ) -> Result<(), TunnelError> {
        for orb_id in orb_ids {
            let _ = self.shelf.remove(orb_id);
        }
        let _ = self.keystore.remove_by_parent(parent_id);
        self.journal.rollback_ingestion(parent_id, reason)
    }
}

fn is_iso_date(value: &str) -> bool {
    let bytes = value.as_bytes();
    if bytes.len() != 10 || bytes[4] != b'-' || bytes[7] != b'-' {
        return false;
    }
    let digits = [0, 1, 2, 3, 5, 6, 8, 9];
    if digits.iter().any(|&index| !bytes[index].is_ascii_digit()) {
        return false;
    }

    let year = match value[0..4].parse::<u16>() {
        Ok(year) => year,
        Err(_) => return false,
    };
    let month = match value[5..7].parse::<u8>() {
        Ok(month @ 1..=12) => month,
        _ => return false,
    };
    let day = match value[8..10].parse::<u8>() {
        Ok(day) => day,
        Err(_) => return false,
    };
    let days_in_month = match month {
        1 | 3 | 5 | 7 | 8 | 10 | 12 => 31,
        4 | 6 | 9 | 11 => 30,
        2 if year % 4 == 0 && (year % 100 != 0 || year % 400 == 0) => 29,
        2 => 28,
        _ => unreachable!("month was validated above"),
    };
    (1..=days_in_month).contains(&day)
}

struct SealedChain {
    key_id: String,
    orb_ids: Vec<String>,
}
