import Config

demo_mode = System.get_env("VENTURI_UI_DEMO") == "true"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :venturi_ui, VenturiUiWeb.Endpoint,
  # Demo mode bypasses OIDC, so development always remains loopback-only.
  http: [
    ip: {127, 0, 0, 1},
    port: String.to_integer(System.get_env("PORT") || "4000")
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "5aIkjCb9Z8y6NEGR0uq4+AFr5b3dlJ15lNqkVSpbhfVDzJVLAb5DmA9TEbNAhcwe",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:venturi_ui, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:venturi_ui, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :venturi_ui, VenturiUiWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"lib/venturi_ui_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :venturi_ui, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Local portfolio demos may bypass OIDC only in the development environment.
# This is never loaded by production releases; do not set this variable for
# anything other than a local demonstration.
config :venturi_ui, :oidc_test_bypass, demo_mode
config :venturi_ui, :demo_mode, demo_mode

config :venturi_ui, :venturi_api,
  base_url: System.get_env("VENTURI_API_URL") || "http://127.0.0.1:9271",
  api_key: System.get_env("VENTURI_API_KEY"),
  namespace: System.get_env("VENTURI_NAMESPACE") || "default"
