use crate::storage::permissions::restrict_database_files;
use crate::types::error::TunnelError;
use rusqlite::{params, Connection};

/// Exit gate keystore — the only place raw encryption keys exist in the system.
///
/// Separate database file, separate directory, restricted permissions (chmod 600).
/// Only two callers are permitted:
///   WRITE → tunnel.rs / Gate3 (deposits key immediately after encryption)
///   READ  → retrieval.rs / Exit Gate 1 (reads key for decryption)
///
/// The Librarian holds key_id pointers only — never raw keys.
/// Nothing else in the system touches this store.
pub struct Keystore {
    conn: Connection,
}

impl Keystore {
    /// Open (or create) the keystore at the given path.
    /// In production: path should be a separate directory with chmod 600.
    pub fn open(path: &str) -> Result<Self, TunnelError> {
        let conn = Connection::open(path).map_err(|_e| TunnelError::KeystoreInaccessible)?;

        conn.execute_batch(
            "
            PRAGMA journal_mode=WAL;
            PRAGMA synchronous=NORMAL;
            CREATE TABLE IF NOT EXISTS keys (
                key_id     TEXT PRIMARY KEY,
                parent_id  TEXT NOT NULL,
                raw_key    BLOB NOT NULL,
                created_at TEXT NOT NULL
            );
            CREATE INDEX IF NOT EXISTS idx_keys_parent ON keys(parent_id);
        ",
        )
        .map_err(|e| TunnelError::DatabaseError(e.to_string()))?;

        restrict_database_files(path)?;

        Ok(Self { conn })
    }

    /// Deposit a chain key. Called by Gate3 immediately after encryption.
    /// key_id: UUID v4 generated by Gate3.
    /// parent_id: the chain this key belongs to.
    /// raw_key: 32-byte ChaCha20 key — never leaves this store after deposit.
    pub fn deposit(
        &self,
        key_id: &str,
        parent_id: &str,
        raw_key: &[u8; 32],
    ) -> Result<(), TunnelError> {
        let now = now_iso();
        self.conn
            .execute(
                "INSERT OR REPLACE INTO keys (key_id, parent_id, raw_key, created_at)
             VALUES (?1, ?2, ?3, ?4)",
                params![key_id, parent_id, raw_key.as_slice(), now],
            )
            .map_err(|e| TunnelError::DatabaseError(e.to_string()))?;
        Ok(())
    }

    /// Retrieve a chain key by key_id. Called by Exit Gate 1 for decryption.
    pub fn retrieve(&self, key_id: &str) -> Result<[u8; 32], TunnelError> {
        let raw: Vec<u8> = self
            .conn
            .query_row(
                "SELECT raw_key FROM keys WHERE key_id = ?1",
                params![key_id],
                |row| row.get(0),
            )
            .map_err(|_| TunnelError::KeystoreInaccessible)?;

        raw.try_into()
            .map_err(|_| TunnelError::DatabaseError("key blob wrong length".into()))
    }

    /// Retrieve a chain key by parent_id. Used during rollback cleanup.
    /// Returns None if no key exists for this chain (already cleaned up).
    pub fn retrieve_by_parent(&self, parent_id: &str) -> Result<Option<String>, TunnelError> {
        let result = self.conn.query_row(
            "SELECT key_id FROM keys WHERE parent_id = ?1 LIMIT 1",
            params![parent_id],
            |row| row.get::<_, String>(0),
        );
        match result {
            Ok(key_id) => Ok(Some(key_id)),
            Err(rusqlite::Error::QueryReturnedNoRows) => Ok(None),
            Err(e) => Err(TunnelError::DatabaseError(e.to_string())),
        }
    }

    /// Remove a chain key by parent_id. Called when a chain ejects to dataset
    /// at 90-day expiry, or during rollback of a failed ingestion.
    pub fn remove_by_parent(&self, parent_id: &str) -> Result<(), TunnelError> {
        self.conn
            .execute("DELETE FROM keys WHERE parent_id = ?1", params![parent_id])
            .map_err(|e| TunnelError::DatabaseError(e.to_string()))?;
        Ok(())
    }
}

fn now_iso() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    format!("{}Z", secs)
}
